In [1]:
from kan import KAN
import torch
from torch.utils.data import DataLoader, TensorDataset
from MLP2layers import NeuralNetwork, test_loop, train_loop

In [30]:
device = 'cpu'
model = NeuralNetwork().to(device)
print(model)
print(model.state_dict())
layers = list(*model.children())
print(list(*model.children()))
# print([(layer.weight, layer.bias) for layer in layers if isinstance(layer, torch.nn.Linear)])
# print(layers[0].weight.data)
# print(layers[0].weight)
# y = layers[0].weight[:,0]*10 + layers[0].bias*1
# print(y, y.shape)
x = torch.randn(3, 4)
y = layers[1](x)
print(x)
print(y)

NeuralNetwork(
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=2, out_features=3, bias=True)
    (1): ReLU()
    (2): Linear(in_features=3, out_features=1, bias=True)
  )
)
OrderedDict({'linear_relu_stack.0.weight': tensor([[ 0.3908,  0.0546],
        [-0.6740,  0.5043],
        [-0.0594,  0.0731]]), 'linear_relu_stack.0.bias': tensor([-0.4274, -0.1292, -0.1197]), 'linear_relu_stack.2.weight': tensor([[-0.3333,  0.0446,  0.1365]]), 'linear_relu_stack.2.bias': tensor([-0.5251])})
[Linear(in_features=2, out_features=3, bias=True), ReLU(), Linear(in_features=3, out_features=1, bias=True)]
tensor([[-1.0390, -0.3543, -0.0980, -0.1043],
        [ 0.6320, -0.6206,  1.7642, -1.1398],
        [-1.9654, -1.1951,  0.5893, -0.2925]])
tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.6320, 0.0000, 1.7642, 0.0000],
        [0.0000, 0.0000, 0.5893, 0.0000]])


In [8]:
x = torch.randn(3,4)
print(x)
print(x[:,:,None])
print(x[:,:,None].shape)
print(x[:,:,None].expand(-1,-1,2))  # expand along new dimension
print(x[:,:,None].expand(-1,-1,2).shape)

tensor([[-1.1035, -0.6549,  1.6589, -0.0890],
        [ 1.1517, -1.0559, -0.3240,  0.1826],
        [-1.1554,  0.9979, -0.0188, -1.0599]])
tensor([[[-1.1035],
         [-0.6549],
         [ 1.6589],
         [-0.0890]],

        [[ 1.1517],
         [-1.0559],
         [-0.3240],
         [ 0.1826]],

        [[-1.1554],
         [ 0.9979],
         [-0.0188],
         [-1.0599]]])
torch.Size([3, 4, 1])
tensor([[[-1.1035, -1.1035],
         [-0.6549, -0.6549],
         [ 1.6589,  1.6589],
         [-0.0890, -0.0890]],

        [[ 1.1517,  1.1517],
         [-1.0559, -1.0559],
         [-0.3240, -0.3240],
         [ 0.1826,  0.1826]],

        [[-1.1554, -1.1554],
         [ 0.9979,  0.9979],
         [-0.0188, -0.0188],
         [-1.0599, -1.0599]]])
torch.Size([3, 4, 2])
